-- public.loan definition

-- Drop table

-- DROP TABLE public.loan;

CREATE TABLE public.loan (
                             loan_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             amount numeric NOT NULL,
                             rate numeric NOT NULL,
                             loan_period int4 NOT NULL,
                             start_date date NOT NULL,
                             CONSTRAINT loan_pk PRIMARY KEY (loan_id)
);


-- public.payment definition

-- Drop table

-- DROP TABLE public.payment;

CREATE TABLE public.payment (
                                payment_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                payment_date date NOT NULL,
                                amount numeric NOT NULL,
                                loan_id int4 NOT NULL,
                                CONSTRAINT payment_pk PRIMARY KEY (payment_id),
                                CONSTRAINT payment_fk FOREIGN KEY (loan_id) REFERENCES public.loan(loan_id)
);