-- public.loan definition

-- Drop table

-- DROP TABLE public.loan;

CREATE TABLE public.loan (
	loan_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	amount numeric NOT NULL,
	rate numeric NOT NULL,
	loan_period int4 NOT NULL,
	start_date date NOT NULL,
	CONSTRAINT loan_pk null
);


-- public.repayment definition

-- Drop table

-- DROP TABLE public.repayment;

CREATE TABLE public.repayment (
	repayment_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	repayment_date date NOT NULL,
	percentage numeric NOT NULL,
	debt numeric NOT NULL,
	loan_id int4 NOT NULL,
	CONSTRAINT repayment_pk PRIMARY KEY (repayment_id),
	CONSTRAINT repayment_fk FOREIGN KEY (loan_id) REFERENCES public.loan(loan_id)
);